version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_loja
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: LOJA
      MYSQL_USER: loja_user
      MYSQL_PASSWORD: loja_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/infra/sql/db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  mysql_data:
